name: Build

on:
  push:
    tags: [ 'v*.*.*' ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      docker-registry: ${{ startsWith(github.ref, 'refs/tags/v') && 'docker.io' || 'ghcr.io' }}
      docker-username: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.DOCKERHUB_USERNAME || github.actor }}
    steps:
      - name: Set outputs
        run: echo "Set outputs"
      
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: 20

  #     - name: Run tests
  #       run: echo "Run tests"
  #     - run: yarn install
  #     - run: yarn test --watch=false

  docker:
    needs: test
    uses: UtopikGoodies/github-workflow/.github/workflows/docker.yml@update
    with:
      registry: ${{ needs.setup.outputs.docker-registry }}
      username: ${{ needs.setup.outputs.docker-username }}
    secrets:
      password: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.DOCKERHUB_TOKEN || secrets.GITHUB_TOKEN }}
